[package]
name = "lsm-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
anyhow="1.*.*"
byteorder = "1.5.0"
tempfile = "3.3.0"
crossbeam-skiplist = "0.1"
bytes = "1.0"
crc32fast = "1.3"
crossbeam-channel = "0.5.15"
tracing = "0.1"
tracing-subscriber = "0.3"
rand = "0.8"
