[package]
name = "lsm-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
log="0.4.*"
simplelog="0.12.2"
bincode = "1.3.3"
serde = {version ="1.0.217",features = ["derive"]}
byteorder = "1.5.0" 
